create table "public"."Exercise" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "exercise_name" text,
    "muscle_group" text
);


alter table "public"."Exercise" enable row level security;

create table "public"."Goals" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "weight" real,
    "height" real,
    "goal" text
);


alter table "public"."Goals" enable row level security;

create table "public"."Health Issues" (
    "client_id" bigint not null,
    "health_issue" text not null,
    "client_name" text
);


alter table "public"."Health Issues" enable row level security;

create table "public"."Plans Subscribed" (
    "user_id" bigint not null,
    "plan_id" bigint not null
);


alter table "public"."Plans Subscribed" enable row level security;

create table "public"."Users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "email" text not null,
    "first_name" text,
    "last_name" text,
    "phone_number" text,
    "dob" date,
    "password" text,
    "gender" text,
    "user_type" text,
    "goal_id" bigint
);


alter table "public"."Users" enable row level security;

create table "public"."Workout Exercises Stats" (
    "workout_id" bigint not null,
    "exercise_id" bigint not null,
    "reps" bigint,
    "duration" real,
    "accuracy" real
);


alter table "public"."Workout Exercises Stats" enable row level security;

create table "public"."Workout History" (
    "workout_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "plan_id" bigint,
    "client_id" bigint,
    "duration" real,
    "accuracy" real
);


alter table "public"."Workout History" enable row level security;

create table "public"."Workout Plan Exercises" (
    "exercise_id" bigint not null,
    "plan_id" bigint not null,
    "reps" bigint,
    "duration" real
);


alter table "public"."Workout Plan Exercises" enable row level security;

create table "public"."Workout Plan" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "plan_trainer" bigint,
    "workout_type" text
);


alter table "public"."Workout Plan" enable row level security;

CREATE UNIQUE INDEX "Exercise_pkey" ON public."Exercise" USING btree (id);

CREATE UNIQUE INDEX "Goals_pkey" ON public."Goals" USING btree (id);

CREATE UNIQUE INDEX "Health Issues_pkey" ON public."Health Issues" USING btree (client_id, health_issue);

CREATE UNIQUE INDEX "Plans Subscribed_pkey" ON public."Plans Subscribed" USING btree (user_id, plan_id);

CREATE UNIQUE INDEX "Users_email_key" ON public."Users" USING btree (email);

CREATE UNIQUE INDEX "Users_id_key" ON public."Users" USING btree (id);

CREATE UNIQUE INDEX "Users_pkey" ON public."Users" USING btree (id);

CREATE UNIQUE INDEX "Workout Exercises Stats_pkey" ON public."Workout Exercises Stats" USING btree (workout_id, exercise_id);

CREATE UNIQUE INDEX "Workout History_pkey" ON public."Workout History" USING btree (workout_id);

CREATE UNIQUE INDEX "Workout Plan Exercises_pkey" ON public."Workout Plan Exercises" USING btree (exercise_id, plan_id);

CREATE UNIQUE INDEX "Workout Plan_pkey" ON public."Workout Plan" USING btree (id);

alter table "public"."Exercise" add constraint "Exercise_pkey" PRIMARY KEY using index "Exercise_pkey";

alter table "public"."Goals" add constraint "Goals_pkey" PRIMARY KEY using index "Goals_pkey";

alter table "public"."Health Issues" add constraint "Health Issues_pkey" PRIMARY KEY using index "Health Issues_pkey";

alter table "public"."Plans Subscribed" add constraint "Plans Subscribed_pkey" PRIMARY KEY using index "Plans Subscribed_pkey";

alter table "public"."Users" add constraint "Users_pkey" PRIMARY KEY using index "Users_pkey";

alter table "public"."Workout Exercises Stats" add constraint "Workout Exercises Stats_pkey" PRIMARY KEY using index "Workout Exercises Stats_pkey";

alter table "public"."Workout History" add constraint "Workout History_pkey" PRIMARY KEY using index "Workout History_pkey";

alter table "public"."Workout Plan Exercises" add constraint "Workout Plan Exercises_pkey" PRIMARY KEY using index "Workout Plan Exercises_pkey";

alter table "public"."Workout Plan" add constraint "Workout Plan_pkey" PRIMARY KEY using index "Workout Plan_pkey";

alter table "public"."Health Issues" add constraint "Health Issues_client_id_fkey" FOREIGN KEY (client_id) REFERENCES "Users"(id) not valid;

alter table "public"."Health Issues" validate constraint "Health Issues_client_id_fkey";

alter table "public"."Plans Subscribed" add constraint "Plans Subscribed_plan_id_fkey" FOREIGN KEY (plan_id) REFERENCES "Workout Plan"(id) not valid;

alter table "public"."Plans Subscribed" validate constraint "Plans Subscribed_plan_id_fkey";

alter table "public"."Plans Subscribed" add constraint "Plans Subscribed_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "Users"(id) not valid;

alter table "public"."Plans Subscribed" validate constraint "Plans Subscribed_user_id_fkey";

alter table "public"."Users" add constraint "Users_email_key" UNIQUE using index "Users_email_key";

alter table "public"."Users" add constraint "Users_goal_id_fkey" FOREIGN KEY (goal_id) REFERENCES "Goals"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Users" validate constraint "Users_goal_id_fkey";

alter table "public"."Users" add constraint "Users_id_key" UNIQUE using index "Users_id_key";

alter table "public"."Workout Exercises Stats" add constraint "Workout Exercises Stats_exercise_id_fkey" FOREIGN KEY (exercise_id) REFERENCES "Exercise"(id) not valid;

alter table "public"."Workout Exercises Stats" validate constraint "Workout Exercises Stats_exercise_id_fkey";

alter table "public"."Workout Exercises Stats" add constraint "Workout Exercises Stats_workout_id_fkey" FOREIGN KEY (workout_id) REFERENCES "Workout History"(workout_id) not valid;

alter table "public"."Workout Exercises Stats" validate constraint "Workout Exercises Stats_workout_id_fkey";

alter table "public"."Workout History" add constraint "Workout History_client_id_fkey" FOREIGN KEY (client_id) REFERENCES "Users"(id) not valid;

alter table "public"."Workout History" validate constraint "Workout History_client_id_fkey";

alter table "public"."Workout History" add constraint "Workout History_plan_id_fkey" FOREIGN KEY (plan_id) REFERENCES "Workout Plan"(id) not valid;

alter table "public"."Workout History" validate constraint "Workout History_plan_id_fkey";

alter table "public"."Workout Plan Exercises" add constraint "Workout Plan Exercises_exercise_id_fkey" FOREIGN KEY (exercise_id) REFERENCES "Exercise"(id) not valid;

alter table "public"."Workout Plan Exercises" validate constraint "Workout Plan Exercises_exercise_id_fkey";

alter table "public"."Workout Plan Exercises" add constraint "Workout Plan Exercises_plan_id_fkey" FOREIGN KEY (plan_id) REFERENCES "Workout Plan"(id) not valid;

alter table "public"."Workout Plan Exercises" validate constraint "Workout Plan Exercises_plan_id_fkey";

alter table "public"."Workout Plan" add constraint "Workout Plan_plan_trainer_fkey" FOREIGN KEY (plan_trainer) REFERENCES "Users"(id) not valid;

alter table "public"."Workout Plan" validate constraint "Workout Plan_plan_trainer_fkey";


